bstatePath: ./.yarn/build-state.yml

cacheFolder: ./.yarn/cache

cloneConcurrency: 2

compressionLevel: mixed

defaultLanguageName: node

defaultProtocol: "npm:"

defaultSemverRangePrefix: ^

enableInlineHunks: true

enableScripts: true

globalFolder: ./.yarn/global

httpRetry: 3

httpTimeout: 60000

immutablePatterns:
  - "**/.pnp.*"

initFields:

  homepage: "https://github.com/goldeimer/goldeimer#readme"

initLicense: BSD-2-Clause

initScope: "@goldeimer"

installStatePath: ./.yarn/install-state.gz

lockfileFilename: ./yarn.lock

networkConcurrency: 8

nmHoistingLimits: none

nodeLinker: pnp

npmAuthToken: ffffffff-ffff-ffff-ffff-ffffffffffff

npmPublishAccess: public

npmRegistryServer: "https://registry.yarnpkg.com"

pnpDataPath: ./.yarn.pnp.data.json

pnpFallbackMode: none

pnpMode: strict

pnpShebang: "#!/usr/bin/env node"

pnpUnpluggedFolder: ./.yarn/unplugged

preferAggregateCacheInfo: false

preferInteractive: true

preferTruncatedLines: false

progressBarStyle: default

virtualFolder: ./.yarn/$$virtual

yarnPath: .yarn/releases/yarn-2.4.0.cjs
