bstatePath: ./.yarn/build-state.yml

cacheFolder: ./.yarn/cache

cloneConcurrency: 2

compressionLevel: mixed

defaultLanguageName: node

defaultProtocol: "npm:"

defaultSemverRangePrefix: ^

enableInlineHunks: true

enableScripts: true

globalFolder: ./.yarn/global

httpRetry: 3

httpTimeout: 60000

immutablePatterns:
  - "**/.pnp.*"

initFields:
  homepage: "https://github.com/goldeimer/goldeimer#readme"

initLicense: BSD-2-Clause

initScope: "@goldeimer"

initVersion: "0.0.1"

installStatePath: ./.yarn/install-state.gz

networkConcurrency: 8

nmHoistingLimits: none

nodeLinker: pnp

npmAlwaysAuth: false

npmPublishAccess: public

npmPublishRegistry: "https://npm.pkg.github.com"

npmRegistryServer: "https://registry.yarnpkg.com"

packageExtensions:
  reakit-warning@*:
    peerDependencies:
      react-dom: "^16 | ^17"
  use-query-params@*:
    peerDependencies:
      query-string: "^6.14"

pnpDataPath: ./.pnp.data.json

pnpFallbackMode: none

pnpEnableInlining: false

pnpMode: strict

pnpShebang: "#!/usr/bin/env node"

pnpUnpluggedFolder: ./.yarn/unplugged

preferAggregateCacheInfo: false

preferInteractive: true

preferTruncatedLines: false

progressBarStyle: default

telemetryInterval: 2

telemetryUserId: "@goldeimer"

virtualFolder: ./.yarn/$$virtual

yarnPath: .yarn/releases/yarn-2.4.1.cjs
