const DAYS_PER_MONTH = 30
const PIECES_PER_ROLL = 150
const ROLLS_PER_PACKAGE = 8
const SUBSCRIPTION_PERIODS_IN_MONTHS = [1, 2, 3, 6]
const SUBSCRIPTION_SIZES_IN_PACKAGES = [9, 27, 81]

export {
    DAYS_PER_MONTH,
    PIECES_PER_ROLL,
    ROLLS_PER_PACKAGE,
    SUBSCRIPTION_PERIODS_IN_MONTHS,
    SUBSCRIPTION_SIZES_IN_PACKAGES
}
