import { TsConfig } from '../../schema'

export const advanced: TsConfig.CompilerOptions41 = {
    allowUnreachableCode: false,
    allowUnusedLabels: false,
    assumeChangesOnlyAffectDirectDependencies: false,
    charset: 'utf-8',
    disableReferencedProjectLoad: false,
    disableSizeLimit: true,
    disableSolutionSearching: false,
    disableSourceOfProjectReferenceRedirect: false,
    emitBOM: false,
    extendedDiagnostics: false,
    forceConsistentCasingInFileNames: true,
    importsNotUsedAsValues: 'error',
    listEmittedFiles: true,
    listFiles: true,
    maxNodeModuleJsDepth: 0,
    noEmitHelpers: false,
    noEmitOnError: false,
    noImplicitUseStrict: false,
    noLib: false,
    noResolve: false,
    noStrictGenericChecks: false,
    preserveConstEnums: true,
    resolveJsonModule: true,
    skipLibCheck: true,
    stripInternal: false,
    suppressExcessPropertyErrors: false,
    suppressImplicitAnyIndexErrors: false,
    traceResolution: false,
    useDefineForClassFields: true
}
