version: '3.7'

secrets:
    secret_jtl_db_name:
        file: ./secrets/secret_jtl_db_name.txt
    secret_jtl_db_password:
        file: ./secrets/secret_jtl_db_password.txt
    secret_jtl_db_user:
        file: ./secrets/secret_jtl_db_user.txt

    secret_wordpress_db_name:
        file: ./secrets/secret_wordpress_db_name.txt
    secret_wordpress_db_password:
        file: ./secrets/secret_wordpress_db_password.txt
    secret_wordpress_db_user:
        file: ./secrets/secret_wordpress_db_user.txt

    secret_wordpress_table_prefix:
        file: ./secrets/secret_wordpress_table_prefix.txt

services:
    # TODO: Combined RDS host for both schemas?
    db_jtl:
        image: mysql:5.7
        restart: always
        volumes:
            - ./sql/jtl.init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./run/data/db/jtl:/var/lib/mysql
        secrets:
            - secret_jtl_db_name
            - secret_jtl_db_password
            - secret_jtl_db_user
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE_FILE: /run/secrets/secret_jtl_db_name
            MYSQL_PASSWORD_FILE: /run/secrets/secret_jtl_db_password
            MYSQL_USER_FILE: /run/secrets/secret_jtl_db_user

    db_wp:
        image: mysql:5.7
        restart: always
        volumes:
            - ./sql/wordpress.init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./run/data/db/wp:/var/lib/mysql
        ports:
            - 3307:3306
        secrets:
            - secret_wordpress_db_name
            - secret_wordpress_db_password
            - secret_wordpress_db_user
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE_FILE: /run/secrets/secret_wordpress_db_name
            MYSQL_PASSWORD_FILE: /run/secrets/secret_wordpress_db_password
            MYSQL_USER_FILE: /run/secrets/secret_wordpress_db_user

    php_fpm_wp:
        # `php-fpm` services requests over port 9000
        image: wordpress:4.9-fpm
        depends_on:
            - db_jtl
            - db_wp
        restart: always
        volumes:
            - ./etc/php-uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - ./run/wordpress:/var/www/html
        extra_hosts:
            # facilitate loopback requests
            - "localhost:172.18.0.1"
            - "goldeimer.de:172.18.0.1"
            - "www.goldeimer.de:172.18.0.1"
        secrets:
            - secret_wordpress_db_name
            - secret_wordpress_db_password
            - secret_wordpress_db_user
            - secret_wordpress_table_prefix
        environment:
            WORDPRESS_DB_HOST: db_wp:3306
            WORDPRESS_DB_NAME_FILE: /run/secrets/secret_wordpress_db_name
            WORDPRESS_DB_PASSWORD_FILE: /run/secrets/secret_wordpress_db_password
            WORDPRESS_DB_USER_FILE: /run/secrets/secret_wordpress_db_user
            WORDPRESS_TABLE_PREFIX_FILE: /run/secrets/secret_wordpress_table_prefix

    php_apache_merchant_map:
        # TODO:
        # - switch to httpd w/ mod_wsgi to facilitate a Python backend
        # - build from own config, w/ mod_rewrite, etc. enabled
        image: php:apache
        restart: always
        working_dir: /var/www/html
        volumes:
            - ./../merchant-map:/var/www/html
        extra_hosts:
            - "map.goldeimer.de:127.0.0.1"
        hostname: map.goldeimer.de

    nginx:
        image: nginx
        depends_on:
            - php_fpm_wp
            - php_apache_merchant_map
        restart: always
        volumes:
            - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./run/wordpress:/var/www/html
            - ./run/log/nginx:/var/log/nginx

    https-portal:
        image: steveltn/https-portal:1
        depends_on:
            - nginx
        ports:
            - 80:80
            - 443:443
        restart: always
        volumes:
            - ./run/ssl-certs:/var/lib/https-portal
        environment:
            DOMAINS: 'www.goldeimer.lc -> http://nginx:80, map.goldeimer.lc -> http://nginx:80'
            STAGE: local
            FORCE_RENEW: 'true'
            CLIENT_MAX_BODY_SIZE: 64M
