# Generated by Django 3.0.6 on 2020-05-20 08:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
            ],
            options={
                'verbose_name': 'Taxonomie',
                'verbose_name_plural': 'Taxonomien',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='map.Taxonomy')),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terme',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=4, max_digits=7, verbose_name='Längengrad')),
                ('longitude', models.DecimalField(db_index=True, decimal_places=4, max_digits=7, verbose_name='Breitengrad')),
                ('address_city', models.CharField(max_length=50, verbose_name='Stadt')),
                ('address_country', models.CharField(choices=[('de', 'Deutschland'), ('li', 'Liechtenstein'), ('at', 'Österreich'), ('ch', 'Schweiz')], max_length=2, verbose_name='Land')),
                ('address_line1', models.CharField(max_length=100, verbose_name='Straße & Hausnummer (Adresszeile 1)')),
                ('address_line2', models.CharField(max_length=100, null=True, verbose_name='Addresszusatz (Adresszeile 2)')),
                ('address_zip_code', models.CharField(max_length=7, verbose_name='Postleitzahl')),
                ('description', models.CharField(max_length=1023, null=True, verbose_name='Freie Beschreibung')),
                ('url', models.URLField(null=True, verbose_name='Webseite (URL)')),
                ('terms', models.ManyToManyField(related_name='terms', to='map.Term')),
            ],
            options={
                'verbose_name': 'Eintrag',
                'verbose_name_plural': 'Einträge',
            },
        ),
    ]
