# Generated by Django 3.0.6 on 2020-05-20 07:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
            ],
            options={
                'verbose_name': 'Taxonomie',
                'verbose_name_plural': 'Taxonomien',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='map.Taxonomy')),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terme',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('terms', models.ManyToManyField(related_name='terms', to='map.Term')),
            ],
            options={
                'verbose_name': 'Eintrag',
                'verbose_name_plural': 'Einträge',
            },
        ),
    ]
